### POST request to the submit URL
POST https://localhost:8000/submit
Content-Type: text/plain

Hello

### GET request to the display URL
GET https://localhost:8000/display

### GET request to the main URL
GET https://localhost:8000/
